---
name: Remove all releases

on:
  workflow_dispatch:

jobs:
  Cleanup:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout Repo'
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: larryjoelane/delete-release-action@v1.0.24
        with:
          release-name: 'jammy'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/KEY.gpg
          tag_name: jammy
          body: Apt repo for Ubuntu 22.04 Jammy Jellyfish
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: larryjoelane/delete-release-action@v1.0.24
        with:
          release-name: 'noble'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/KEY.gpg
          tag_name: noble
          body: Apt repo for Ubuntu 24.04 Noble Numbat
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: larryjoelane/delete-release-action@v1.0.24
        with:
          release-name: 'oracular'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/KEY.gpg
          tag_name: oracular
          body: Apt repo for Ubuntu 24.04 Noble Numbat
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: larryjoelane/delete-release-action@v1.0.24
        with:
          release-name: 'bookworm'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/KEY.gpg
          tag_name: bookworm
          body: Apt repo for Debian 12 Bookworm
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: larryjoelane/delete-release-action@v1.0.24
        with:
          release-name: 'sid'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/KEY.gpg
          tag_name: sid
          body: Apt repo for Debian Unstable
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
