---
name: Create t2fanrd package

on:
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 -di | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Configure GIT
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global advice.detachedHead false

      - name: Install cargo-deb
        run: |
          cargo install cargo-deb
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Build package
        run: |
          SERVICE_URL=https://raw.githubusercontent.com/t2linux/fedora/main/t2fanrd/t2fanrd.service
          REPO=https://github.com/GnomedDev/T2FanRD.git
          COMMIT_HASH=5b1c0c10785b8e8dfe124a4d6aaa7c2becdac65c
          REVISION=4
          TARGET=$(mktemp --directory)
          trap 'rm -rf "${TARGET}"' EXIT

          set -e
          sudo apt-get install -qy cargo debhelper
          git clone "${REPO}" "${TARGET}"
          curl -fssL "${SERVICE_URL}" -o t2fanrd.service

          (
            set -e
            pushd "${TARGET}"
            mkdir debian
            curl -fssL "${SERVICE_URL}" -o debian/service

            echo '[package.metadata.deb]' >>Cargo.toml
            echo 'maintainer = "Aditya Garg"' >>Cargo.toml
            echo 'maintainer-scripts = "debian/"' >>Cargo.toml
            echo 'license-file = ["LICENCE"]' >>Cargo.toml
            echo 'extended-description = "Simple Fan Daemon for T2 Macs"' >>Cargo.toml
            echo 'depends = "$auto"' >>Cargo.toml
            echo 'section = "utility"' >>Cargo.toml
            echo 'priority = "optional"' >>Cargo.toml
            echo 'systemd-units = { enable = true }' >>Cargo.toml

            cargo-deb --deb-revision "${REVISION}"
            mv target/debian/t2fanrd_*.deb "$(dirs -l +1)/"
          )
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Sign and release
        id: publish
        run: |
          dpkg-scanpackages --multiversion . >Packages
          gzip -k -f Packages
          apt-ftparchive release . >Release
          gpg --default-key "${GPG_SIGNING_EMAIL}" -abs -o - Release > Release.gpg
          gpg --default-key "${GPG_SIGNING_EMAIL}" --clearsign -o - Release > InRelease
          cd ${{ github.workspace }}
          git add .
          git commit -m "Update t2fanrd to ${VERSION}"
        env:
          GPG_SIGNING_EMAIL: ${{ secrets.GPG_SIGNING_EMAIL }}

      - name: Push changes to the repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
