---
name: Create tiny-dfr package

on:
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout Repo'
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 -di | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Get the source code
        id: publish
        run: |
          REPO=https://github.com/AdityaGarg8/tiny-dfr.git
          COMMIT_HASH=aeee3360420cd5a8f2c178d49999bf577728bb42
          VERSION=0.2.0-2
          curl -s --compressed "https://adityagarg8.github.io/t2-ubuntu-repo/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg >/dev/null
          sudo curl -s --compressed -o /etc/apt/sources.list.d/t2.list "https://adityagarg8.github.io/t2-ubuntu-repo/t2.list"
          sudo apt update -y
          #sudo apt upgrade -y
          sudo apt-get install -y gir1.2-coglpango-1.0 gir1.2-pango-1.0 libcogl-pango-dev libghc-gi-pango-dev \
          libghc-pango-dev libghc-yi-frontend-pango-dev libpango1.0-dev libudev-dev libinput-dev apple-touchbar
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git clone ${REPO}
          cd tiny-dfr
          git checkout ${COMMIT_HASH}
          cp ${{ github.workspace }}/.github/patches/*.patch ./
          git am ./*.patch
          cargo b --release
          mkdir deb
          cd deb
          mkdir usr
          cd usr
          mkdir bin
          mkdir src
          cd ..
          cd ..
          mkdir -p ./etc/tiny-dfr
          cp ./share/tiny-dfr/config.toml ./etc/tiny-dfr/config.toml
          cp -r ./etc ./deb
          cp -r ./share ./deb/usr
          cp ./target/release/tiny-dfr ./deb/usr/bin
          cp -r /usr/src/apple-touchbar-0.1 ./deb/usr/src
          mv ./deb/etc/udev/rules.d/* ./deb/usr/share/tiny-dfr
          mv ./deb/etc/systemd/system/* ./deb/usr/share/tiny-dfr
          cp ${{ github.workspace }}/.github/scripts/touchbar ./deb/usr/bin
          chmod a+x ./deb/usr/bin/tiny-dfr
          chmod a+x ./deb/usr/bin/touchbar
          cd deb
          mkdir DEBIAN
          cd DEBIAN

          echo "Package: tiny-dfr" > control
          echo "Version: ${VERSION}" >> control
          echo "Maintainer: Aditya Garg" >> control
          echo "Architecture: amd64" >> control
          echo "Description: Function row daemon for touchbar on Macs" >> control
          echo "Depends: systemd, dkms" >> control

          echo "if [ -f /etc/tiny-dfr/config.toml ]" > preinst
          echo "then" >> preinst
          echo "cp /etc/tiny-dfr/config.toml /etc/tiny-dfr/config.toml.orj" >> preinst
          echo "fi" >> preinst

          echo "if [ -f /etc/tiny-dfr/config.toml.orj ]" > postinst
          echo "then" >> postinst
          echo "touchbar --restore" >> postinst
          echo "fi" >> postinst
          echo 'if [ ! -f /etc/modprobe.d/tiny-dfr.conf ]' >> postinst
          echo 'then' >> postinst
          echo "for rule in /usr/share/tiny-dfr/*.rules" >> postinst
          echo "do" >> postinst
          echo 'rule_file=$(echo $rule | rev | cut -d "/" -f 1 | rev)' >> postinst
          echo 'cp -v /usr/share/tiny-dfr/$rule_file /etc/udev/rules.d/$rule_file' >> postinst
          echo "done" >> postinst
          echo "for service in /usr/share/tiny-dfr/*.service" >> postinst
          echo "do" >> postinst
          echo 'service_file=$(echo $service | rev | cut -d "/" -f 1 | rev)' >> postinst
          echo 'cp -v /usr/share/tiny-dfr/$service_file /etc/systemd/system/$service_file' >> postinst
          echo "done" >> postinst
          echo "systemctl enable --now tiny-dfr.service" >> postinst
          echo "else" >> postinst
          echo "dkms add -m apple-touchbar -v 0.1" >> postinst
          echo "dkms build -m apple-touchbar -v 0.1 && dkms install -m apple-touchbar -v 0.1 || true" >> postinst
          echo "fi" >> postinst
          echo "echo -e \"\\nYou may have to restart your Mac in case of a new installation\"" >> postinst

          echo 'if [ -f /etc/systemd/system/tiny-dfr.service ]' > prerm
          echo "then" >> prerm
          echo "systemctl disable --now tiny-dfr.service" >> prerm
          echo "fi" >> prerm
          echo "for rule in /usr/share/tiny-dfr/*.rules" >> prerm
          echo "do" >> prerm
          echo 'rule_file=$(echo $rule | rev | cut -d "/" -f 1 | rev)' >> prerm
          echo 'if [ -f /etc/udev/rules.d/$rule_file ]' >> prerm
          echo "then" >> prerm
          echo 'rm -v /etc/udev/rules.d/$rule_file' >> prerm
          echo 'fi' >> prerm
          echo "done" >> prerm
          echo "for service in /usr/share/tiny-dfr/*.service" >> prerm
          echo "do" >> prerm
          echo 'service_file=$(echo $service | rev | cut -d "/" -f 1 | rev)' >> prerm
          echo 'if [ -f /etc/udev/rules.d/$service_file ]' >> prerm
          echo "then" >> prerm
          echo 'rm -v /etc/udev/rules.d/$service_file' >> prerm
          echo 'fi' >> prerm
          echo "done" >> prerm
          echo 'if [ -f /etc/modprobe.d/tiny-dfr.conf ]' >> prerm
          echo 'then' >> prerm
          echo "dkms remove -m apple-touchbar -v 0.1 --all || true" >> prerm
          echo "fi" >> prerm

          chmod 755 ./preinst
          chmod 755 ./postinst
          chmod 755 ./prerm

          cd ${{ github.workspace }}/tiny-dfr
          dpkg-deb --build --root-owner-group -Zgzip deb

          mv ./deb.deb ${{ github.workspace }}
          cd ${{ github.workspace }}
          # Packages & Packages.gz
          rm ./tiny-dfr*.deb
          dpkg-name ./deb.deb
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
          # Release, Release.gpg & InRelease
          apt-ftparchive release . > Release
          gpg --default-key "${GPG_SIGNING_EMAIL}" -abs -o - Release > Release.gpg
          gpg --default-key "${GPG_SIGNING_EMAIL}" --clearsign -o - Release > InRelease
          cd ${{ github.workspace }}
          rm -r ./tiny-dfr
          git add .
          git commit -m "Update tiny-dfr to ${VERSION}"
        env:
          GPG_SIGNING_EMAIL: ${{ secrets.GPG_SIGNING_EMAIL }}
      - name: Push changes to the repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
